# System
CONFIG_ZMK_KEYBOARD_NAME="Keeby"
#CONFIG_MAIN_STACK_SIZE=2048
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Enable Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Underglow LEDs (Fixed from RGB Matrix)
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_SPI=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Set default Underglow behavior (Blue default)
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_HUE=240
# CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_SAT=100
# CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_VAL=50
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=200

# Enable ZMK Display Subsystem
CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
# CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_I2C=y
CONFIG_SSD1306=y

# Enable Default ZMK Widgets
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
# CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# CONFIG_ZMK_WIDGET_WPM_STATUS=n

# Enable NFC pins as GPIOs (Needed for P0.09 and P0.10)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable BT TX power plus 8
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_BATTERY_REPORTING=y
# CONFIG_ZMK_KSCAN_COMPOSITE=y
# CONFIG_ZMK_KSCAN_DIRECT_GPIO=y
