# System
CONFIG_ZMK_KEYBOARD_NAME="Keeby"

# Enable Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable LEDs
CONFIG_ZMK_RGB_MATRIX=y
CONFIG_ZMK_RGB_MATRIX_EXT_POWER=n
CONFIG_WS2812_STRIP=y

# Set default RGB behavior
CONFIG_ZMK_RGB_MATRIX_DEFAULT_HUE=240  # Blue
CONFIG_ZMK_RGB_MATRIX_DEFAULT_SAT=100
CONFIG_ZMK_RGB_MATRIX_DEFAULT_VAL=50

# Enable NFC pins as GPIOs (Needed for P0.09 and P0.10)
CONFIG_NFCT_PINS_AS_GPIOS=y
