# System
CONFIG_ZMK_KEYBOARD_NAME="Keeby"
CONFIG_ZMK_SPLIT=n

# Enable Encoders
#CONFIG_EC11=y
#CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Underglow LEDs (Fixed from RGB Matrix)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Set default Underglow behavior (Blue default)
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_HUE=240
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_SAT=100
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_VAL=50
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=100

# Enable NFC pins as GPIOs (Needed for P0.09 and P0.10)
#CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable BT TX power plus 8
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_BATTERY_REPORTING=n
CONFIG_BOARD_ENABLE_DCDC=n
