file_format: "1"
id: keeby
name: Keeby
type: shield
url: https://github.com/codecooker1/keeby
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - keeby_left
  - keeby_right